name: SneakyPoses
version: '${version}'
main: com.sneakyposes.SneakyPoses
description: A Minecraft Paper plugin designed to control player poses.
api-version: '1.21'
authors: [Team Sneakymouse]
website: https://rawb.tv

dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE
      required: false